// Pre-build: regenerate src/data/articles.generated.ts from content/blog/*.md so
// the homepage "Latest Articles" teaser (src/sections/Articles.tsx) stays in sync
// with real posts. Runs BEFORE `vite build`, since the teaser is bundled into the SPA.
//
// Shows the latest 3 published posts. With zero posts the array is empty and the
// teaser section renders nothing (its own guard), so the live homepage is unchanged
// until the first post exists.

import fs from 'node:fs';
import path from 'node:path';
import { loadPosts, ROOT } from './blog-lib.mjs';

const OUT = path.join(ROOT, 'src', 'data', 'articles.generated.ts');
const LIMIT = 3;

const posts = loadPosts().slice(0, LIMIT);

const entries = posts
  .map((p) =>
    `  {
    tag: ${JSON.stringify(p.tag)},
    title: ${JSON.stringify(p.title)},
    excerpt: ${JSON.stringify(p.description)},
    date: ${JSON.stringify(p.dateDisplay)},
    href: ${JSON.stringify(p.path)},
  },`
  )
  .join('\n');

const file = `// AUTO-GENERATED by scripts/prebuild-blog.mjs — do not edit by hand.
// Source of truth: content/blog/*.md. Regenerated on every \`npm run dev\` and \`npm run build\`.
import type { Article } from './articles';

export const ARTICLES: Article[] = [
${entries}
];
`;

fs.writeFileSync(OUT, file);
console.log(`[blog] wrote homepage teaser manifest: ${posts.length} article(s)`);
