// AUTO-GENERATED by scripts/prebuild-blog.mjs — do not edit by hand.
// Source of truth: content/blog/*.md. Regenerated on every `npm run dev` and `npm run build`.
import type { Article } from './articles';

export const ARTICLES: Article[] = [
  {
    tag: "Demand Generation",
    title: "Why Referrals Aren't Enough to Grow a Service Business Anymore",
    excerpt: "Referrals stall because you control none of the inputs — volume, timing or fit. Here's the referral ceiling, and what growing past it actually takes.",
    date: "31 Aug 2026",
    href: "/blog/referrals-arent-enough",
  },
];
