// AUTO-GENERATED by scripts/prebuild-blog.mjs — do not edit by hand.
// Source of truth: content/blog/*.md. Regenerated on every `npm run dev` and `npm run build`.
import type { Article } from './articles';

export const ARTICLES: Article[] = [
  {
    tag: "Demand Generation",
    title: "Case Study: 2.5× More Qualified Funeral-Plan Opportunities on 29.5% Less Ad Spend in 30 Days",
    excerpt: "In 30 days, Compare Funerals went from 24 to 60 qualified funeral-plan opportunities a month on 29.5% less Meta spend. Cost per qualified lead fell 71.7%. What changed.",
    date: "3 Sep 2026",
    href: "/blog/compare-funerals-30-day-case-study",
  },
  {
    tag: "Demand Generation",
    title: "How Much Does It Cost to Market a Service Business in 2026?",
    excerpt: "Established service businesses spend 5–10% of revenue on marketing: a $2,500–$10,000/month retainer or an in-house hire, plus ad spend. The real ranges, and the number that matters more.",
    date: "3 Sep 2026",
    href: "/blog/service-business-marketing-cost",
  },
  {
    tag: "Demand Generation",
    title: "What Is a Qualified Sales Call — and Why It's the Only Marketing Metric That Matters",
    excerpt: "A qualified sales call is a prepared conversation with a buyer who fits, has the problem, and can pay. Here's how to define it, cost it, and manufacture more.",
    date: "2 Sep 2026",
    href: "/blog/qualified-sales-calls",
  },
];
